# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_rfPbGi0ntKXM1IKhn_i9d0SAz0bGyv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

datos=pd.read_csv('/content/mnist_train.csv')
datos=datos.dropna()
y=datos['label']
x=datos.drop('label', axis=1)

org=TSNE(n_components=2,random_state=42)
x2d=org.fit_transform(x)
plt.figure(figsize=(10,8))

grafica=plt.scatter(x2d[:,0],x2d[:,1], c=y,cmap='tab10',s=1)
plt.colorbar(grafica, ticks=range(10))
plt.title('Mapa')
plt.show()

xculster7=x[y==7]
org7=TSNE(n_components=2, random_state=42)
x2d7=org7.fit_transform(xculster7)
plt.figure(figsize=(10,8))
grafica=plt.scatter(x2d7[:,0],x2d7[:,1],c=y[y==7],cmap='tab10',s=1)
plt.title('Cluster de 7')
plt.show()